### ISSUE TITLE
ImportError: cannot import name 'discrete' from 'gym.envs.toy_text'

### ISSUE THREAD

**Issue by Mercuron** [mimoralea/gym-walk#3]
Installed via pip
Error after this command:
`env = gym.make('SlipperyWalkFive-v0')`

**Comment by mimoralea** [comment]
Install `gym<=0.20`.

They have been making recent breaking changes.

**Comment by mimoralea** [comment]
I just merged a contribution that should fix this, in case you want to test that out instead.
