### ISSUE TITLE
should this be published to PyPI?

### ISSUE THREAD

**Issue by MatthewCaseres** [mimoralea/gym-walk#5]
unsure if this is necessary or desirable - https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by MatthewCaseres** [comment]
maybe not

**Comment by mimoralea** [comment]
We can publish it. Maybe useful to some... I don't know how to do it, but my main issue is that we would have to make it compatible with the latest gym and maybe even "gymnasium." See: https://github.com/Farama-Foundation/Gymnasium

I'm starting a second edition of the book, and I can see how updating everything may be beneficial.
